version: '3.8'

services:
  micropython-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
